name: study_group
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  provider: ^6.0.3  # Version de provider (vérifiez la dernière version)
  table_calendar: ^3.0.2  # Version de table_calendar (vérifiez la dernière version)
  cloud_firestore: ^5.6.0  
  async: ^2.11.0
  boolean_selector: ^2.1.1
  characters: ^1.3.0
  clock: ^1.1.1
  collection: ^1.19.0
  fake_async: ^1.3.1
  intl: ^0.19.0
  leak_tracker: ^10.0.7
  leak_tracker_flutter_testing: ^3.0.8
  matcher: ^0.12.16+1
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  path: ^1.9.0
  source_span: ^1.10.0
  stack_trace: ^1.12.0
  stream_channel: ^2.1.2
  string_scanner: ^1.3.0
  term_glyph: ^1.2.1
  test_api: ^0.7.3
  vm_service: ^14.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
